config/routes.rb
Rails.application.routes.draw do
	resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @content = (Kramdown::Document.new(@article.content).to_html).html_safe
    @name = (Kramdown::Document.new(@article.name).to_html).html_safe
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end
  
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:name, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
  <%= form_for(@article) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :content %>

<div id="editor">
  <%= f.text_field :content %>
</div>

  <%= f.submit %>
  <% end %>

<script>
  $( document ).ready(function() {
    var editor = ace.edit("editor");
  });
</script>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<%= link_to "New Article", new_article_path%>

<% @articles.each do |article| %>
<h2><%= article.name %></h2>
<p><%= article.content %></p>

<%= link_to "Show", article_path(article)%>
<%= link_to "Edit", edit_article_path(article)%>

<%= link_to "Delete", article_path(article),
method: :delete,
data: { confirm: "Are you sure?" } %>

<% end %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<h2><%= @name %></h2>
<p><%= @content %></p>
<%= link_to "Back to index", articles_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>